version: "3.9"

services:
  mariadb:
    image: mariadb:10.5.8-focal
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: upsense
    volumes:
      - ./mysql/default.sql:/docker-entrypoint-initdb.d/default.sql

  api:
    build:
      dockerfile: ./api/Dockerfile
      context: ./
    image: upsense-api-dev:latest
    ports:
      - 8443:8443
    volumes: # Remove this if going to build for production
      - ./api:/var/www/api
    links:
      - mariadb:mysql
      - influxdb

  influxdb:
    image: influxdb:1.8.3
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_LOG_ENABLED: 0
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb/storage:/var/lib/influxdb

  mqtt-broker:
    build:
      dockerfile: ./mqtt/Dockerfile
      context: ./
    image: upsense-mqtt-broker-dev:latest
    ports:
      - 1883:1883
    volumes: # Remove this if going to build for production
      - ./mqtt:/var/www/mqtt_broker
    links:
      - influxdb
