version: '3'

services:
    app:
        # Upsense web app
        container_name: upsense_app
        build:
            context: ./
            dockerfile: docker/development/app.dockerfile
        image: upsense_app:latest
        volumes:
            - ./storage:/var/www/storage
        env_file: '.env.dev'
        environment:
            - "DB_HOST=upsense"
#        depends_on:
#            - mysql

    # nginx web server
    web:
        container_name: upsense_nginx
        image: upsense_web:latest
        build:
            context: ./
            dockerfile: docker/development/web.dockerfile
        volumes:
            - ./storage/logs/:/var/log/nginx
            - ./:/var/www/html
        working_dir: /var/www/html

        ports:
            - 8990:80
            # - 443:443

    # mysql database
#    mysql:
#        container_name: upsense_mysql
#        image: mysql:8.0
#        volumes:
#            - dbdata:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_HOST: '${DB_HOST}'
#            MYSQL_DATABASE: '${DB_DATABASE}'
#            MYSQL_USER: '${DB_USERNAME}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#        ports:
#            - 8991:3306

volumes:
    dbdata:
        # driver: local

